
project_id = "rnpcygrrxeeqphdjuesh"
[api]
enabled = true

[functions.generate-research-report]
verify_jwt = false

[functions.predict-stock-price]
verify_jwt = false

[functions.analyze-growth-insights]
verify_jwt = false

[functions.cache-company-documents]
verify_jwt = false

[functions.get-finnhub-news]
verify_jwt = false

[functions.get-stock-data]
verify_jwt = false

[functions.generate-transcript-highlights]
verify_jwt = false

[functions.fetch-earnings-transcripts]
verify_jwt = false

[functions.execute-sql]
verify_jwt = false

[functions.optimize-database]
verify_jwt = false

[functions.get-finnhub-company-news]
verify_jwt = false

[functions.get-finnhub-social-sentiment]
verify_jwt = false
