
project_id = "rnpcygrrxeeqphdjuesh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.generate-research-report]
verify_jwt = false

[functions.predict-stock-price]
verify_jwt = false

[functions.analyze-growth-insights]
verify_jwt = false

[functions.cache-company-documents]
verify_jwt = false

[functions.get-finnhub-news]
verify_jwt = false

[functions.get-stock-data]
verify_jwt = false

[functions.generate-transcript-highlights]
verify_jwt = false

[functions.fetch-earnings-transcripts]
verify_jwt = false

[functions.execute-sql]
verify_jwt = false

[functions.optimize-database]
verify_jwt = false

[functions.get-finnhub-company-news]
verify_jwt = false

[functions.get-finnhub-social-sentiment]
verify_jwt = false

# Commented out as these functions are no longer in use
# [functions.get-fmp-acquisition-ownership]
# verify_jwt = false

# [functions.get-fmp-insider-trading-stats]
# verify_jwt = false
