
// A comprehensive list of common stock tickers and their company names
export const commonTickers = [
  // Major US Indices
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust" },
  { symbol: "QQQ", name: "Invesco QQQ Trust (Nasdaq-100 Index)" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF" },
  
  // S&P 500 Components
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc. Class B" },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated" },
  { symbol: "PG", name: "Procter & Gamble Company" },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "HD", name: "Home Depot Inc." },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "CRM", name: "Salesforce Inc." },
  { symbol: "KO", name: "Coca-Cola Company" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "CSCO", name: "Cisco Systems Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "PM", name: "Philip Morris International Inc." },
  { symbol: "MRK", name: "Merck & Co. Inc." },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "GE", name: "General Electric Company" },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "ISRG", name: "Intuitive Surgical Inc." },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "DIS", name: "Walt Disney Company" },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "NOW", name: "ServiceNow Inc." },
  { symbol: "GS", name: "Goldman Sachs Group Inc." },
  { symbol: "QCOM", name: "Qualcomm Incorporated" },
  { symbol: "TXN", name: "Texas Instruments Incorporated" },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "PLTR", name: "Palantir Technologies Inc." },
  { symbol: "PGR", name: "Progressive Corporation" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices Inc." },
  { symbol: "UBER", name: "Uber Technologies Inc." },
  { symbol: "BKNG", name: "Booking Holdings Inc." },
  { symbol: "AXP", name: "American Express Company" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "UNP", name: "Union Pacific Corporation" },
  { symbol: "BSX", name: "Boston Scientific Corporation" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "GILD", name: "Gilead Sciences Inc." },
  { symbol: "NEE", name: "NextEra Energy Inc." },
  { symbol: "BLK", name: "BlackRock Inc." },
  { symbol: "CMCSA", name: "Comcast Corporation" },
  { symbol: "LOW", name: "Lowe's Companies Inc." },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "TJX", name: "TJX Companies Inc." },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "SCHW", name: "Charles Schwab Corporation" },
  { symbol: "TMUS", name: "T-Mobile US Inc." },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc." },
  { symbol: "FI", name: "Fiserv Inc." },
  { symbol: "AMAT", name: "Applied Materials Inc." },
  { symbol: "ADP", name: "Automatic Data Processing Inc." },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company" },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "BA", name: "Boeing Company" },
  { symbol: "PANW", name: "Palo Alto Networks Inc." },
  { symbol: "MMC", name: "Marsh & McLennan Companies" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "PLD", name: "Prologis Inc." },
  { symbol: "ADI", name: "Analog Devices Inc." },
  { symbol: "ETN", name: "Eaton Corporation plc" },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "BX", name: "Blackstone Inc." },
  { symbol: "MU", name: "Micron Technology Inc." },
  { symbol: "LRCX", name: "Lam Research Corporation" },
  { symbol: "ICE", name: "Intercontinental Exchange Inc." },
  { symbol: "LMT", name: "Lockheed Martin Corporation" },
  { symbol: "SO", name: "Southern Company" },
  { symbol: "AMT", name: "American Tower Corporation" },
  { symbol: "MO", name: "Altria Group Inc." },
  { symbol: "ELV", name: "Elevance Health Inc." },
  { symbol: "NKE", name: "NIKE Inc." },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "CME", name: "CME Group Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "MDLZ", name: "Mondelez International Inc." },
  { symbol: "DUK", name: "Duke Energy Corporation" },
  { symbol: "UPS", name: "United Parcel Service Inc." },
  { symbol: "WELL", name: "Welltower Inc." },
  { symbol: "CI", name: "The Cigna Group" },
  { symbol: "ANET", name: "Arista Networks Inc." },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { symbol: "EQIX", name: "Equinix Inc." },
  { symbol: "SHW", name: "Sherwin-Williams Company" },
  { symbol: "WM", name: "Waste Management Inc." },
  { symbol: "CVS", name: "CVS Health Corporation" },
  { symbol: "MCK", name: "McKesson Corporation" },
  { symbol: "PH", name: "Parker-Hannifin Corporation" },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc." },
  { symbol: "GEV", name: "GE Vernova Inc." },
  { symbol: "MMM", name: "3M Company" },
  { symbol: "KKR", name: "KKR & Co. Inc." },
  { symbol: "ORLY", name: "O'Reilly Automotive Inc." },
  { symbol: "TT", name: "Trane Technologies plc" },
  { symbol: "CL", name: "Colgate-Palmolive Company" },
  { symbol: "TDG", name: "TransDigm Group Incorporated" },
  { symbol: "ZTS", name: "Zoetis Inc." },
  
  // Additional Popular Stocks
  { symbol: "HOOD", name: "Robinhood Markets Inc." },
  { symbol: "COIN", name: "Coinbase Global Inc." },
  { symbol: "RBLX", name: "Roblox Corporation" },
  { symbol: "SOFI", name: "SoFi Technologies Inc." },
  { symbol: "RIVN", name: "Rivian Automotive Inc." },
  { symbol: "LCID", name: "Lucid Group Inc." },
  { symbol: "SNOW", name: "Snowflake Inc." },
  { symbol: "DDOG", name: "Datadog Inc." },
  { symbol: "ZM", name: "Zoom Video Communications Inc." },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "PINS", name: "Pinterest Inc." },
  { symbol: "SNAP", name: "Snap Inc." },
  { symbol: "U", name: "Unity Software Inc." },
  { symbol: "AI", name: "C3.ai Inc." },
  { symbol: "SPOT", name: "Spotify Technology S.A." },
  { symbol: "ARM", name: "Arm Holdings plc" },
  { symbol: "ABNB", name: "Airbnb Inc." },
  { symbol: "NTDOY", name: "Nintendo Co., Ltd." },
  { symbol: "SONY", name: "Sony Group Corporation" },
  { symbol: "DASH", name: "DoorDash Inc." },
  { symbol: "OKTA", name: "Okta Inc." },
  { symbol: "MSTR", name: "MicroStrategy Incorporated" },
  { symbol: "GME", name: "GameStop Corp." },
  { symbol: "AMC", name: "AMC Entertainment Holdings Inc." },
  { symbol: "BABA", name: "Alibaba Group Holding Limited" },
  { symbol: "NIO", name: "NIO Inc." },
  { symbol: "XPEV", name: "XPeng Inc." },
  { symbol: "LI", name: "Li Auto Inc." }
];
